services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: LeagueOfLegendsDataBase
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database/patch_14.16.1.sql:/docker-entrypoint-initdb.d/patch_14.16.1.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/publish
    working_dir: /app
    command: dotnet watch run
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__LeagueOfLegendsDatabase: "Server=db;Database=LeagueOfLegendsDataBase;User=root;Password=${MYSQL_ROOT_PASSWORD};"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`leagueoflegendsbr.site`)"
      - "traefik.http.routers.web.rule=Host(`app.leagueoflegendsbr.site`)"
      - "traefik.http.services.web.loadbalancer.server.port=5050"
    ports:
      - "5050:5050"
    restart: on-failure

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

volumes:
  db-data:
